### PR TITLE
Add option to cancel jobs on KeyboardInterrupt

### LINKED ISSUE #1: Feature: Option to cancel jobs
Sometimes you start a job and realize that you messed something up in the configuration. A nice extension of the behaviour of Ctrl + C would be to ask the user whether to cancel (all|pending|running|none) jobs

### PR DESCRIPTION
**Pull request by dwoiwode**
Had no time to test yet, but this should implement #1 with basic functionality. I hope I find the time to test this in the next weeks...

closes #1

### CODE REVIEW

**Comment by creinders** [comment]
Cool! Let me know if it's working.

**Comment by dwoiwode** [comment]
Needed some refinement, but is now ready to go I guess. 
Added a 10s sleep in the example and tested it with `python example/my_app.py -m +i="range(0,40)" hydra.launcher.gres="gpu:turing:1" hydra.launcher.mem_gb=48`.

UNKNOWN Jobs are now also seen as pending.

**Comment by creinders** [comment]
It works great! I think we can remove the _cancel all running jobs_ option, as the pending jobs would be kept scheduled and executed after the launcher has been terminated.

**Comment by dwoiwode** [comment]
Yeah that was the point of this option, but I get the point why this is useless

**Comment by creinders** [comment]
Thank you for implementing the feature! I just released a new version.

**Pull request merged**
